# Generated by Django 5.0.4 on 2024-05-14 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Ismi')),
                ('lastname', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Xarid vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Xolat')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer', verbose_name='Mijoz')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Soni')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Xarid vaqti')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order', verbose_name='Xarid')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Maxsulot')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('city', models.CharField(max_length=255, verbose_name='Shahar')),
                ('district', models.CharField(max_length=50, verbose_name='Tuman')),
                ('zipcode', models.CharField(max_length=100, verbose_name='Pochta kodi')),
                ('mobile', models.CharField(max_length=100, verbose_name='Mobil raqami')),
                ('email', models.EmailField(max_length=100, verbose_name='Email manzili')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer', verbose_name='Mijoz')),
            ],
        ),
    ]
